[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rayon = "1.10.0"
rng = "0.1.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
